---
name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get current tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Re-Tag image sommerfeldio/jq from :release-candidate to :${{ steps.vars.outputs.tag }} and :latest
        run: |
          VERSION_TAG="$(cut -d "v" -f2 <<< ${{ steps.vars.outputs.tag }})"

          docker pull sommerfeldio/jq:release-candidate

          docker tag sommerfeldio/jq:release-candidate sommerfeldio/jq:latest
          docker tag sommerfeldio/jq:release-candidate sommerfeldio/jq:$VERSION_TAG

          docker push sommerfeldio/jq:latest
          docker push sommerfeldio/jq:$VERSION_TAG

  docker-hub-description:
    runs-on: ubuntu-latest
    needs: release-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Convert README from asciidoc to markdown for DockerHub description
        run: |
          sudo apt-get install -y pandoc asciidoc
          asciidoc -b docbook README.adoc
          pandoc -f docbook -t markdown_strict README.xml -o README.md
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: sommerfeldio/jq
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md

  on-failure:
    runs-on: ubuntu-latest
    needs: docker-hub-description
    if: failure()

    steps:
      - name: Send pipeline status to Slack
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: failure
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: C0438TFQNPM # pipelines channel
